- name: Install build-essential on Debian/Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Ensure build-essential is installed
      apt:
        name: build-essential
        state: present
        update_cache: yes

    - name: Create /etc/modules-load.d/k8s.conf
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        mode: "0644"

    - name: Load overlay module
      modprobe:
        name: overlay
        state: present

    - name: Load br_netfilter module
      modprobe:
        name: br_netfilter
        state: present

    - name: Ensure overlay is in /etc/modules
      lineinfile:
        path: /etc/modules
        line: "overlay"
        state: present

    - name: Ensure br_netfilter is in /etc/modules
      lineinfile:
        path: /etc/modules
        line: "br_netfilter"
        state: present

    # - name: Create /etc/sysctl.d/k8s.conf with required settings
    #   copy:
    #     dest: /etc/sysctl.d/k8s.conf
    #     content: |
    #       net.bridge.bridge-nf-call-iptables  = 1
    #       net.bridge.bridge-nf-call-ip6tables = 1
    #       net.ipv4.ip_forward                 = 1
    #     mode: "0644"

    # - name: Apply sysctl settings
    #   command: sysctl --system

    - name: add net.ipv4.ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: add net.bridge.bridge-nf-call-iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: add net.bridge.bridge-nf-call-ip6tables
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: "1"
        sysctl_set: true
        state: present
        reload: true

    - name: Install apt-transport-https, ca-certificates, curl, gnupg, gpg
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - gpg
          - jq
        state: present
        update_cache: yes

    - name: Install package for longhorn
      apt:
        name:
          - open-iscsi
          - nfs-common
          - cryptsetup
          - dmsetup
          - grep
          - util-linux
        state: present
        update_cache: yes

    - name: Ensure iscsi_tcp module loads on boot
      copy:
        dest: /etc/modules-load.d/iscsi.conf
        content: |
          iscsi_tcp

    - name: Load iscsi_tcp kernel module
      modprobe:
        name: iscsi_tcp
        state: present
